# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MoE-Frontend-Develop
    url: https://frontend.develop.moe-digital-id.apps.atixlabs.xyz
  - name: MoE-Backend-Develop
    url: https://api.develop.moe-digital-id.apps.atixlabs.xyz/healthcheck
#   - name: MoE-DID-Service-Develop
#     url: https://api-did.develop.moe-digital-id.apps.atixlabs.xyz/healthcheck 

  - name: MoE-Frontend-Staging
    url: https://frontend.staging.moe-digital-id.apps.atixlabs.xyz
  - name: MoE-Backend-Staging
    url: https://api.staging.moe-digital-id.apps.atixlabs.xyz/healthcheck
#   - name: MoE-DID-Service-Staging
#     url: https://api-did.staging.moe-digital-id.apps.atixlabs.xyz/healthcheck 

  - name: MoE-Frontend-UAT-Phase1
    url: https://frontend.uat-phase1.moe-digital-id.apps.atixlabs.xyz
  - name: MoE-Backend-UAT-Phase1
    url: https://api.uat-phase1.moe-digital-id.apps.atixlabs.xyz/healthcheck
#   - name: MoE-DID-Service-UAT-Phase1
#     url: https://api-did.uat-phase1.moe-digital-id.apps.atixlabs.xyz/healthcheck 

  - name: MoE-Frontend-UAT-Phase2
    url: https://frontend.uat-phase2.moe-digital-id.apps.atixlabs.xyz
  - name: MoE-Backend-UAT-Phase2
    url: https://api.uat-phase2.moe-digital-id.apps.atixlabs.xyz/healthcheck
#   - name: MoE-DID-Service-UAT-Phase2
#     url: https://api-did.uat-phase2.moe-digital-id.apps.atixlabs.xyz/healthcheck 

assignees:
  - rechemendiaatix
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /moe-sites-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: moe-sites-status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
